export const imageSizes = {
  // "xs": {
  //   width: 300
  // },
  "sm": {
    width: 480
  },
  "md": {
    width: 640
  },
  "lg": {
    width: 960
  },
  "xl": {
    width: 1280
  },
  "thumb-xs": {
    width: 300,
    height: 300
  },
  "thumb": {
    width: 640,
    height: 640
  }
}

export const drawings = {
  info: {
    title: "Drawings",
    description: "I like the drawing because it is a line, whether a continous or a dashed onem the same as life."
  },
  path: "drawings",
  images: [
    { filename: "Twoface.jpg" },
    { filename: "Act.jpg" },
    { filename: "Between_Two_Planets.jpg" },
    { filename: "Born_in_Nature.jpg" },
    { filename: "Common_Feelings.jpg" },
    { filename: "Crystal_Cloud.jpg" },
    { filename: "Dante_Alighieri.jpg" },
    { filename: "Education.jpg" },
    { filename: "Erotic.jpg" },
    { filename: "Fidelity.jpg" },
    { filename: "Gentle-Soul.jpg" },
    { filename: "Hyper-Population.jpg" },
    { filename: "Inspiration.jpg" },
    { filename: "Intellectual.jpg" },
    { filename: "Intimacy.jpg" },
    { filename: "Kiro-Urdin-Drawing-8.jpg" },
    { filename: "Kiro-Urdin-Drawing-9.jpg" },
    { filename: "Kiro-Urdin-Drawing-10.jpg" },
    { filename: "Kiro-Urdin-Drawing-11.jpg" },
    { filename: "Kiro-Urdin-Drawing-12.jpg" },
    { filename: "Kiro-Urdin-Drawing-13.jpg" },
    { filename: "Kiro-Urdin-Drawing-14.jpg" },
    { filename: "Kiro-Urdin-Drawing-15.jpg" },
    { filename: "Kiro-Urdin-Drawing-16.jpg" },
    { filename: "Kiro-Urdin-Drawing-17.jpg" },
    { filename: "Kiro-Urdin-Drawing-18.jpg" },
    { filename: "Kiro-Urdin-Drawing-19.jpg" },
    { filename: "Kiro-Urdin-Drawing-20.jpg" },
    { filename: "Kiro-Urdin-Drawing-21.jpg" },
    { filename: "Kiro-Urdin-Drawing-22.jpg" },
    { filename: "Kiro-Urdin-Drawing-27.jpg" },
    { filename: "Kiro-Urdin-Drawing-34.jpg" },
    { filename: "Kiro-Urdin-Drawing-36.jpg" },
    { filename: "Kiro-Urdin-Drawing-37.jpg" },
    { filename: "Kiro-Urdin-Drawing-38.jpg" },
    { filename: "Lost_World.jpg" },
    { filename: "Lovely-Girl.jpg" },
    { filename: "Metropolitan_Man.jpg" },
    { filename: "Nostalgia.jpg" },
    { filename: "Nymph.jpg" },
    { filename: "Orgasm.jpg" },
    { filename: "Performance.jpg" },
    { filename: "Power.jpg" },
    { filename: "Solitude.jpg" },
    { filename: "Stone_World.jpg" },
    { filename: "Superman.jpg" },
    { filename: "The_Last_Tree.jpg" },
    { filename: "Thinking_Man.jpg" },
    { filename: "Time.jpg" },
    { filename: "Tree_of_Life.jpg" },
    { filename: "Two_Worlds.jpg" }
  ]
}

export const paintings = {
  info: {
    title: "Paintings",
    description: `Nature in itself is colour. It lives in matter mixed with life.
      So it means that it lives inside and outside of man. Therefore, painting is
      so attractive. Through it man approached the real and the abstract, the concrete
      and the imaginary, depending on the concept.`
  },
  path: "paintings",
  images: [
    { filename: "A-New-Continent-Kiro-Urdin-oil-on-canvas-196x146cm.jpg" },
    { filename: "Abstract_Rhapsody_[Kiro_Urdin,_oil_on_cavas,_120x160cm].jpg" },
    { filename: "Abstract_Vibes_[Kiro_Urdin,_oil_on_canvas,_120x150cm].jpg" },
    { filename: "African_Dream_[Kiro_Urdin,_oil_on_canvas,_130x160].jpg" },
    { filename: "Alexander_the_Great_[Kiro_Urdin,_oil_on_canvas,_120x180cm].jpg" },
    { filename: "Aliance_[Kiro_Urdin,_oil_and_acryl_on_canvas,_180x120cm].jpg" },
    { filename: "Amazon[Kiro_Urdin,_oil_on_canvas,_176x128cm].jpg" },
    { filename: "Aspen_[Kiro_Urdin,_oil_on_canvas,300x200cm].jpg" },
    { filename: "Atlas-Kiro-Urdin-oil-on-canvas-100x130cm.jpg" },
    { filename: "Beggining_of_Love_[Kiro_Urdin,_oil_on_canvas,_130x160cm].jpg" },
    { filename: "Between_Two_[Kiro_Urdin,_oil_on_canvas,_130x180cm].jpg" },
    { filename: "Big_Bang_Theory_[Kiro_Urdin,_oil_on_canvas,_150x200cm].jpg" },
    { filename: "Biodiversity_[Kiro_Urdin,_oil_on_canvas,_190x150cm].jpg" },
    { filename: "Black_Eye_[Kiro_Urdin,_oil_on_canvas,_100x120cm].jpg" },
    { filename: "Blue_Period_[Kiro_Urdin,_oil_on_canvas,_160x130cm].jpg" },
    { filename: "Blue_Reflection_[Kiro_Urdin,_oil_on_canvas,_160x140cm].jpg" },
    { filename: "Blue-Red-Black-Kiro-Urdin-oil-on-canvas-120x150cm.jpg" },
    { filename: "Chips_of_Memory_[Kiro_Urdin,_oil_on_canvas,_110x150cm].jpg" },
    { filename: "Classical-Dance-Kiro-Urdin-oil-on-canvas-80x100cm.jpg" },
    { filename: "Coco_Island_[Kiro_Urdin,_oil_on_canvas,_130x160cm].jpg" },
    { filename: "Corral-Sea-[Kiro_Urdin,_oil-on-canvas,-200x300cm].jpg" },
    { filename: "Crystal-Movement-[Kiro_Urdin,_oil-on-canvas-165x120cm].jpg" },
    { filename: "Cuzco-[Kiro_Urdin,_oil-on-canvas,-130x158cm].jpg" },
    { filename: "Dogona_[Kiro_Urdin,_oil_on_canvas,_400x300cm].jpg" },
    { filename: "Elegance_[Kiro_Urdin,_oil_on_canvas,_150x200cm].jpg" },
    { filename: "Embryos_[Kiro_Urdin,_acrylic_on_paper,_120x160cm].jpg" },
    { filename: "Enigmatic_Woman_[Kiro_Urdin,_oil-and-acrylic-on-canvas,200x150cm].jpg" },
    { filename: "Essential-Things_[Kiro_Urdin,_oil-on-canvas,-160x130cm].jpg" },
    { filename: "Europa_[Kiro_Urdin,_oil_on_canvas,_200x600cm].jpg" },
    { filename: "Exotic-Garden-Kiro-Urdin-oil-on-canvas-130x150cm.jpg" },
    { filename: "Experimental_Music_[Kiro_Urdin,_oil-on-canvas-300x200cm].jpg" },
    { filename: "Fire_of_Love_[Kiro_Urdin,_oil_on_canvas,_90x135cm].jpg" },
    { filename: "First_Emotion_[Kiro_Urdin,_oil_on_canvas,_150x120cm].jpg" },
    { filename: "Flight-of-the-Phoenix-[Kiro_Urdin,_oil-on-cavas,-120x180cm].jpg" },
    { filename: "Freedom_[Kiro_Urdin,_oil_on_canvas,_160x120cm].jpg" },
    { filename: "Futuristic_City_[Kiro_Urdin,_oil_on_canvas,_200x300cm].jpg" },
    { filename: "Futuristic-Man-[Kiro_Urdin,_oil-on-canvas,-180x130cm].jpg" },
    { filename: "Galapagos-Kiro-Urdin-oil-on-canvas-159x138cm.jpg" },
    { filename: "Galaxy-Man-[Kiro_Urdin,_oil-on-canvas-165-x-120-cm].jpg" },
    { filename: "Galician_Red_[Kiro_Urdin,_oil_on_canvas,_160x120cm].jpg" },
    { filename: "Game-[Kiro_Urdin,_oil-on-canvas,-150-x120cm].jpg" },
    { filename: "Good_Thought_[Kiro_Urdin,_oil_on_canvas,_170x120cm].jpg" },
    { filename: "Google_[Kiro_Urdin,_oil_on_canvas,_120x150cm].jpg" },
    { filename: "Green-Garden-[Kiro_Urdin,_oil-on-canvas,-200x300cm].jpg" },
    { filename: "Human_[Kiro_Urdin,_oil_on_canvas,_120x150cm].jpg" },
    { filename: "Humanoid_[Kiro_Urdin,_oil_on_canvas,_130x150cm].jpg" },
    { filename: "Intelligence_[Kiro_Urdin,_oil_on_canvas,_170x140cm].jpg" },
    { filename: "Interior_of_an_Exterior_[Kiro_Urdin,_oil_on_canvas,_120x150cm].jpg" },
    { filename: "Link-Kiro-Urdin-oli-on-canvas.jpg" },
    { filename: "Mandelas_World_[Kiro_Urdin,_acrylic,_150x120cm].jpg" },
    { filename: "Marvelous-World-[Kiro_Urdin,_oil-on-canvas,-120x180cm].jpg" },
    { filename: "Matter_Close_Up_[Kiro_Urdin,_oil_on_canvas,_120x150cm].jpg" },
    { filename: "Maya-Woman-[Kiro_Urdin,_oil-on-canvas,-100x80cm].jpg" },
    { filename: "Memory_of_the_Flora_[Kiro_Urdin,_oil_on_canvas,_130x160cm].jpg" },
    { filename: "Microsoft-[Kiro_Urdin,_oil-on-canvas,-120x200cm].jpg" },
    { filename: "mystical-world-300x200-oil-by-kiro-urdin.jpg" },
    { filename: "New_Continent_[Kiro_Urdin,_oil-on-canvas,_190x150cm].jpg" },
    { filename: "Oceanica_[Kiro_Urdin,_oil-on-canvas,_400x290cm].jpg" },
    { filename: "Opera_[Kiro_Urdin,_oil_on_canvas,_160x140cm].jpg" },
    { filename: "Osmosis_[Kiro_Urdin,_oil_on_canvas,180x160cm].jpg" },
    { filename: "Pantera_[Kiro_Urdin,_acrylic,_150x200].jpg" },
    { filename: "Pharaoh-Times-[Kiro_Urdin,_oil-on-canvas,-150x130-cm].jpg" },
    { filename: "Pharohs_Mistress_[Kiro_Urdin,_oil_on_canvas,_130x180cm].jpg" },
    { filename: "Piano-bar-[Kiro_Urdin,_oil-on-canvas,-170x200cm].jpg" },
    { filename: "Pitch_of_Grass_[Kiro_Urdin,_oil_on_canvas,_70x90cm].jpg" },
    { filename: "Pitch-of-Grass-Kiro-Urdin-oil-on-canvas-70x90cm.jpg" },
    { filename: "Prince_[Kiro_Urdin,_acrylic,_200x150cm].jpg" },
    { filename: "Red_Sea_[Kiro_Urdin,_oil_on_canvas,_200x330cm].jpg" },
    { filename: "Red_Signals_[Kiro_Urdin,_oil_and_acryl_on_canvas,_180x240cm].jpg" },
    { filename: "Red-Circles-[Kiro_Urdin,_oil-and-acryl-on-canvas,-150x120cm].jpg" },
    { filename: "Red-Sea-Kiro-Urdin-oil-on-canvas-330x200cm.jpg" },
    { filename: "Return-to-the-Past-Kiro-Urdin-oil-on-canvas.jpg" },
    { filename: "Rhino_[Kiro_Urdin,_oil_on_canvas,_150x170cm].jpg" },
    { filename: "Rythmical-Movements-[Kiro_Urdin,_oil-on-canvas,-110x140cm].jpg" },
    { filename: "Secret_Love-[Kiro_Urdin,_oil_on_canvas,_145x113cm].jpg" },
    { filename: "Secret_Message_[Kiro_Urdin,_oil_on_cavas,_140x180].jpg" },
    { filename: "Secret-Love-Kiro-Urdin-oil-on-canvas-145x113cm.jpg" },
    { filename: "Simplicity_[Kiro_Urdin,_oil_on_canvas,_100x80cm].jpg" },
    { filename: "Source-of-Life-[Kiro_Urdin,_oil-on-canvas,-300x200cm].jpg" },
    { filename: "Space-and-Lines-Kiro-Urdin-oil-on-canvas-120x180cm.jpg" },
    { filename: "Space-Unity-Kiro-Urdin-oil-on-canvas-300x200cm.jpg" },
    { filename: "Spirals-of-Love-Kiro-Urdin-oil-on-canvas-190x130cm.jpg" },
    { filename: "Spiritual_Life_[Kiro_Urdin,_acrylic,_130x160cm].jpg" },
    { filename: "Spring_Signal_[Kiro_Urdin,_oil_on_canvas,_160x135cm].jpg" },
    { filename: "Steps_of_Time_[Kiro_Urdin,_oil_on_canvas,_400x200cm].jpg" },
    { filename: "Superposition-[Kiro_Urdin,_oil-on-canvas,-130x180cm].jpg" },
    { filename: "Synthesis-II-Kiro-Urdin-oil-on-canvas-40x55cm.jpg" },
    { filename: "Third_Dimension_[Kiro_Urdin,_oil_on_canvas,_120x150cm].jpg" },
    { filename: "Venetian_Woman_[Kiro_Urdin,_oil_on_canvas,_82x100cm].jpg" },
    { filename: "Venezia-Dream-[Kiro_Urdin,_oil-on-canvas,_165x120cm].jpg" },
    { filename: "Volume_and_Space_[Kiro_Urdin,_oil_on_canvas,_150x130cm].jpg" },
    { filename: "Wall-Street-Impresion_[Kiro_Urdin,_oil-on-canvas,-170x200cm].jpg" },
    { filename: "War-of-the-Spirits-[Kiro_Urdin,_oil-on-canvas,-170x280cm].jpg" },
    { filename: "Woman_from_the_Equator_[Kiro_Urdin,_oil_on_canvas,_100x80cm].jpg" },
    { filename: "Yellow-Secret-[Kiro_Urdin,_oil-on-canvas,-200x300cm].jpg" }
  ]
}

export const watercolours = {
  info: {
    title: "Watercolours",
    description: `What is common about the watercolour is the transparency.
      My style of watercolour is somewhat different; I prefer to use several
      layers of texture, similar to the way the oil paintings are done.`
  },
  path: "watercolours",
  images: [
    { filename: "Alien-Kiro-Urdin-watercolour-24x35cm.jpg" },
    { filename: "Amazon-Queen-by-Kiro-Urdin-watercolour,-55x75cm.jpg" },
    { filename: "Antigona,-watercolour,-25x35cm.jpg" },
    { filename: "Ascend-watercolour,-90x150cm.jpg" },
    { filename: "Black-and-Red-Expression-by-Kiro-Urdin-watercolour,-30x40cm.jpg" },
    { filename: "Black-Kingdom-Kiro-Urdin-watercolour-35x25cm.jpg" },
    { filename: "Blue-Galaxy-by-Kiro-Urdin-watercolour,-105x75cm.jpg" },
    { filename: "Cartier-by-Kiro-Urdin-watercolour,-75x50cm.jpg" },
    { filename: "Color-Drops-Kiro-Urdin-watercolour.jpg" },
    { filename: "Connection-by-Kiro-Urdin-watercolour,-105x75cm.jpg" },
    { filename: "Coral-Life-by-Kiro-Urdin-watercolour,75x105cm.jpg" },
    { filename: "Crystal-World-Kiro-Urdin-watercolour-55x75cm.jpg" },
    { filename: "Deep-in-the-Ocean-Kiro-Urdin-watercolour-50x40cm.jpg" },
    { filename: "Dogon-Man-Kiro-Urdin-watercolour,36x36cm.jpg" },
    { filename: "Dogon-Woman-Kiro-Urdin-watercolour,-77x115cm.jpg" },
    { filename: "Drama-by-Kiro-Urdin-watercolour,-181.jpg" },
    { filename: "Ecstasy-by-Kiro-Urdin-watercolour,25x35cm.jpg" },
    { filename: "Ethiopia-Kiro-Urdin-watercolour.jpg" },
    { filename: "Experience-Kiro-Urdin-watercolour-50x40cm.jpg" },
    { filename: "Extravagance-by-Kiro-Urdin-watercolour,75x55cm.jpg" },
    { filename: "Feeling-of-Surprise-by-Kiro-Urdin-watercolour,58x85cm.jpg" },
    { filename: "Gentle-Gift-by-Kiro-Urdin-watercolour,-55x75cm.jpg" },
    { filename: "Happy-World-by-Kiro-Urdin-watercolour,-75x50cm.jpg" },
    { filename: "Harmony-Kiro-Urdin-watercolour-35x25cm.jpg" },
    { filename: "Illusion-by-Kiro-Urdin-watercolour,61x101cm.jpg" },
    { filename: "In-Bed-Kiro-Urdin-watercolour,55x75cm.jpg" },
    { filename: "Jazz-Musician-by-Kiro-Urdin-watercolour,-40x60cm.jpg" },
    { filename: "Liason-Kiro-Urdin-watercolour.jpg" },
    { filename: "Lucy-by-Kiro-Urdin-watercolour-35x25cm.jpg" },
    { filename: "Magic-Circle-by-Kiro-Urdin-watercolour-35x25cm.jpg" },
    { filename: "Moment-of-Craziness-by-Kiro-Urdin-watercolour,-55x70cm.jpg" },
    { filename: "Movement-by-Kiro-Urdin-watercolour,-75x53cm.jpg" },
    { filename: "Movement-in-Space-by-Kiro-Urdin-watercolour,-75x50cm.jpg" },
    { filename: "Mystery-Kiro-Urdin-watercolour2.jpg" },
    { filename: "Mystical-Bird-Kiro-Urdin-watercolour,55x75cm.jpg" },
    { filename: "Neros-Son-Kiro-Urdin-watercolour,25x35cm.jpg" },
    { filename: "Noble-Woman-by-Kiro-Urdin-watercolour,-55x75cm.jpg" },
    { filename: "Nucleus-by-Kiro-Urdin-watercolour,-35x25cm.jpg" },
    { filename: "Pharaohs-Cousin-watercolour,-55x75-cm.jpg" },
    { filename: "Picador-TODO-watercolour,-TODO.jpg" },
    { filename: "Profounder-by-Kiro-Urdin-watercolour,-100x150cm.jpg" },
    { filename: "Rhythm-and-Rhyme-II-watercolour-55x75cm.jpg" },
    { filename: "Ritual-by-Kiro-Urdin-watercolour,55x75cm.jpg" },
    { filename: "Round-World-Kiro-Urdin-watercolour-55x75cm.jpg" },
    { filename: "Rugby-Player-by-Kiro-Urdin-watercolour,55x75cm.jpg" },
    { filename: "Scala-de-Milano-Kiro-Urdin-watercolour,55x75cm.jpg" },
    { filename: "Seduction-Kiro-Urdin-watercolour,55x75cm.jpg" },
    { filename: "Small-Titan-Kiro-Urdin-watercolour,35x35cm.jpg" },
    { filename: "The-Himalayas-watercolor,-143x97-cm.jpg" },
    { filename: "Titan-Kiro-Urdin-watercolour.jpg" },
    { filename: "title-TODO-watercolour,-38x28cm.jpg" },
    { filename: "title-TODO-watercolour,-90x150px.jpg" },
    { filename: "Two-Mondenss,-watercolour,-25x35cm.jpg" },
    { filename: "Wide-Open-Kiro-Urdin-watercolour-106x75cm.jpg" },
    { filename: "Wires-Kiro-Urdin-watercolour-25x35cm.jpg" }
  ]
}

export const sculptures = {
  path: "sculptures",
  info: {
    title: "Sculptures",
    description: `Sculptures, beyond mere observation, beckon to
      be touched — a silent exploration of form that resonates.`
      /* `The essence of sculptures lies not in being looked at
      but in enticing to be touched. It is an exploration of form that
      speaks in silence.`
      */
  },
  images: [
    { filename: "sculptures_cover.jpg" },
    { filename: "sculpture_101.jpg" },
    { filename: "sculpture_01.jpg" },
    { filename: "sculpture_02.jpg" },
    { filename: "sculpture_03.jpg" },
    { filename: "sculpture_04.jpg" },
    { filename: "sculpture_05.jpg" },
    // { filename: "sculpture_06.jpg" },
    { filename: "sculpture_07.jpg" },
    { filename: "sculpture_08.jpg" },
    { filename: "sculpture_09.jpg" },
    { filename: "Sculpture_Kiro_Urdin_Time_Machine.jpg" },
    { filename: "sculpture-kiro-urdin-14.jpg" },
    { filename: "sculpture-kiro-urdin-16.jpg" },
    { filename: "sculpture-kiro-urdin-17.jpg" },
    { filename: "sculpture-kiro-urdin-18.jpg" },
    { filename: "sculpture-kiro-urdin-19.jpg" },
    { filename: "sculpture-kiro-urdin-20.jpg" },
  ]
}

export const ballet = {
  path: "planetarium-dance",
  cover: {
    index: 0
  },
  images: [
    { filename: "debbie_wilson.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-0.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-1.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-2.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-3.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-4.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-5.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-6.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-7.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-8.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-9.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-10.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-11.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-12.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-13.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-14.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-15.jpg" },
    { filename: "Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-16.jpg" },
    { filename: "Planetarium-Dance-Poster-Kiro-Urdin-Debbie-Wilson.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Cover-Kiro-Urdin-and-Debbie-Wilson.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-1.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-2.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-3.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-4.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-5.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-6.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-7.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-9.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-10.jpg" },
    { filename: "UN-60th-Anniversary-Planetarium-Dance-Kiro-Urdin-and-Debbie-Wilson-12.jpg" }
  ]
}

export const people = {
  path: "people",
  images: [
    { filename: "kiro_urdin_and_gerard_meulensteen.jpg" },
    { filename: "Baroness_Daniele-Baccardi_and-Donna_Urdin.jpg" },
    { filename: "Kiro_Urdin_with_Riki_and_Sandra_Portanova1.jpg" },
    { filename: "Kiro_Urdin_with_Mick_Fleetwood.jpg" },
    { filename: "Luciano_Pavarotti_-_Mr.Pieter_van_Vollenhoven_-_Kiro_Urdin_-_Andrea_Griminelli.jpg" },
    { filename: "Kiro_Urdin_with_Henry_Kissinger.jpg" },
    { filename: "Mick_Fleetwood.jpg" },
    { filename: "kiro_urdin_anatoli_karpov_ku_jovan_pavleski.jpg" },
    { filename: "Gerard-Meulensteen2.jpg" },
    { filename: "Kiro_Urdin_with_Brothers_Kocho_and_Vasil.jpg" },
    { filename: "Kiro_Urdin_and_Friend2.jpg" },
    { filename: "Kiro-Urdin-and-Guy-Pas-Geneva.jpg" },
    { filename: "Kiro_Urdin__with_Friends_2.jpg" },
    { filename: "Corinne_Timsit_and_Anatoli_Karpov.jpg" },
    { filename: "Marin-Dimevski2.jpg" },
    { filename: "Donna-Urdin2.jpg" },
    { filename: "Ivan-Mitevski-and-Dragan-Tanevski.jpg" },
    { filename: "Kiro_Urdin_and_Vladimir_Petrovski_Karter.jpg" },
    { filename: "Kiro_Urdin_and_Friend4.jpg" },
    { filename: "Kiro_Urdin_and_Philip.jpg" },
    { filename: "Venko_Serafimov.jpg" },
    { filename: "Donna-Urdin.jpg" },
  ]
}

export const portraits = {
  path: 'portraits',
  images: [
    {
      filename: "Kiro-Urdin-Portrait-1.jpg",
      sizes: {
        thumb: {
          fit: "cover",
          position: "top"
        }
      }
    },
    { filename: "Kiro-Urdin--Portrait-(6).jpg" },
    { filename: "Kiro-Urdin---Portrait-(15).jpg" },
    { filename: "Kiro-Urdin---Portrait-(17).jpg" },
    // { filename: "Kiro-Urdin-Portrait-2-2.jpg" },
    { filename: "Kiro-Urdin-Portrait-2.jpg" },
    { filename: "Kiro-Urdin-Portrait-3.jpg" },
    { filename: "Kiro-Urdin-Portrait-4.jpg" },
    { filename: "Kiro-Urdin-Portrait-5.jpg" },
    { filename: "Kiro-Urdin-Portrait-6.jpg" },
    { filename: "Kiro-Urdin-Portrait-10.jpg" },
    { filename: "Kiro-Urdin-Portrait-12.jpg" },
    { filename: "Kiro-Urdin-Portrait-14.jpg" },
    // { filename: "Kiro-Urdin-Portrait-15.jpg" },
    { filename: "Kiro-Urdin-Portrait-16.jpg" },
  ]
}

export const omoValley = {
  path: "omo-valley",
  images: [
    { filename: "Tribes-of-Omo-Valley-0.jpg" },
    { filename: "Tribes-of-Omo-Valley-1.jpg" },
    { filename: "Tribes-of-Omo-Valley-2.jpg" },
    { filename: "Tribes-of-Omo-Valley-3.jpg" },
    { filename: "Tribes-of-Omo-Valley-4.jpg" },
    { filename: "Tribes-of-Omo-Valley-5.jpg" },
    { filename: "Tribes-of-Omo-Valley-6.jpg" },
    { filename: "Tribes-of-Omo-Valley-7.jpg" },
    { filename: "Tribes-of-Omo-Valley-8.jpg" },
    { filename: "Tribes-of-Omo-Valley-9.jpg" },
    { filename: "Tribes-of-Omo-Valley-10.jpg" },
    { filename: "Tribes-of-Omo-Valley-11.jpg" },
    { filename: "Tribes-of-Omo-Valley-12.jpg" },
    { filename: "Tribes-of-Omo-Valley-13.jpg" },
    { filename: "Tribes-of-Omo-Valley-14.jpg" },
    { filename: "Tribes-of-Omo-Valley-15.jpg" },
    { filename: "Tribes-of-Omo-Valley-16.jpg" },
    { filename: "Tribes-of-Omo-Valley-17.jpg" },
    { filename: "Tribes-of-Omo-Valley-18.jpg" },
    { filename: "Tribes-of-Omo-Valley-19.jpg" },
    { filename: "Tribes-of-Omo-Valley-20.jpg" },
    { filename: "Tribes-of-Omo-Valley-21.jpg" },
    { filename: "Tribes-of-Omo-Valley-22.jpg" },
    { filename: "Tribes-of-Omo-Valley-23.jpg" },
    { filename: "Tribes-of-Omo-Valley-24.jpg" },
    { filename: "Tribes-of-Omo-Valley-25.jpg" },
    { filename: "Tribes-of-Omo-Valley-26.jpg" },
    { filename: "Tribes-of-Omo-Valley-27.jpg" },
    { filename: "Tribes-of-Omo-Valley-28.jpg" },
    { filename: "Tribes-of-Omo-Valley-29.jpg" },
    { filename: "Tribes-of-Omo-Valley-30.jpg" },
    { filename: "Tribes-of-Omo-Valley-31.jpg" },
    { filename: "Tribes-of-Omo-Valley-32.jpg" },
    { filename: "Tribes-of-Omo-Valley-33.jpg" },
    { filename: "Tribes-of-Omo-Valley-34.jpg" },
    { filename: "Tribes-of-Omo-Valley-35.jpg" },
    { filename: "Tribes-of-Omo-Valley-36.jpg" },
    { filename: "Tribes-of-Omo-Valley-37.jpg" },
    { filename: "Tribes-of-Omo-Valley-38.jpg" },
    { filename: "Tribes-of-Omo-Valley-39.jpg" },
    { filename: "Tribes-of-Omo-Valley-40.jpg" },
    { filename: "Tribes-of-Omo-Valley-41.jpg" },
    { filename: "Tribes-of-Omo-Valley-42.jpg" },
    { filename: "Tribes-of-Omo-Valley-Cover.jpg" },
  ]
}

export const planetarium = {
  path: "planetarium",
  images: [
    { filename: "Kiro_Urdin-Ohrid-Macedonia.jpg" },
    { filename: "Kiro_Urdin-Paris-France.jpg" },
    { filename: "Kiro_Urdin-Piza.jpg" },
    { filename: "Kiro_Urdin-Planetaium-Japan.jpg" },
    { filename: "Kiro_Urdin-Planetarium_06.jpg" },
    { filename: "Kiro_Urdin-Planetarium_15.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Atomium-Bruseels.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Berlin.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Big_poster.jpg" },
    { filename: "Kiro_Urdin-Planetarium-China_wall.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Jerusalem1.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Jerusalem2.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Jerusalem3.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Jerusalem4.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Jerusalem5.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Jerusalem6.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Kenya.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Keopsis_Pyramid-Egypt.jpg" },
    { filename: "Kiro_Urdin-Planetarium-London.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Maccu-Picchu.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Mont_Saint-Michel1.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Mont_Saint-Michel2.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Mont_Saint-Michel3.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Nerezi-Macedonia1.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Nerezi-Macedonia2.jpg" },
    { filename: "Kiro_Urdin-Planetarium-New_York.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Nice2.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Nile-Egypt.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Stonehendge.jpg" },
    { filename: "Kiro_Urdin-Planetarium-Thailand.jpg" },
    { filename: "Kiro_Urdin-Plantarium-Luvr.jpg" },
    { filename: "Kiro-Urdin-Berlin-Wall.jpg" },
    { filename: "Kiro-Urdin-Planetarium-Pompei.jpg" },
  ]
}

export const chinaFilmFestival = {
  path: "china-film-festival",
  images: [
    { filename: "China-Nature-Film-Festival-1.jpg" },
    { filename: "China-Nature-Film-Festival-2.jpg" },
    { filename: "China-Nature-Film-Festival-3.jpg" },
    { filename: "China-Nature-Film-Festival-4.jpg" },
    { filename: "China-Nature-Film-Festival-5.jpg" },
    { filename: "China-Nature-Film-Festival-6.jpg" },
    { filename: "China-Nature-Film-Festival-7.jpg" },
    { filename: "China-Nature-Film-Festival-8.jpg" },
    { filename: "China-Nature-Film-Festival-9.jpg" },
    { filename: "China-Nature-Film-Festival-10.jpg" },
    { filename: "China-Nature-Film-Festival-11.jpg" },
    { filename: "China-Nature-Film-Festival-12.jpg" },
    { filename: "China-Nature-Film-Festival-13.jpg" },
    { filename: "China-Nature-Film-Festival-14.jpg" },
    { filename: "China-Nature-Film-Festival-15.jpg" },
    { filename: "China-Nature-Film-Festival-16.jpg" },
    { filename: "China-Nature-Film-Festival-17.jpg" },
    { filename: "China-Nature-Film-Festival-18.jpg" },
    { filename: "China-Nature-Film-Festival-19.jpg" },
    { filename: "China-Nature-Film-Festival-20.jpg" },
    { filename: "China-Nature-Film-Festival-21.jpg" },
    { filename: "China-Nature-Film-Festival-22.jpg" },
    { filename: "China-Nature-Film-Festival-23.jpg" },
    { filename: "China-Nature-Film-Festival-24.jpg" },
    { filename: "China-Nature-Film-Festival-25.jpg" },
    { filename: "China-Nature-Film-Festival-26.jpg" },
    { filename: "China-Nature-Film-Festival-27.jpg" },
    { filename: "China-Nature-Film-Festival-28.jpg" },
    { filename: "China-Nature-Film-Festival-29.jpg" },
    { filename: "China-Nature-Film-Festival-30.jpg" },
    { filename: "China-Nature-Film-Festival-31.jpg" },
    { filename: "China-Nature-Film-Festival-32.jpg" },
    { filename: "China-Nature-Film-Festival-33.jpg" },
    { filename: "China-Nature-Film-Festival-34.jpg" },
    { filename: "China-Nature-Film-Festival-35.jpg" },
    { filename: "China-Nature-Film-Festival-36.jpg" },
    { filename: "China-Nature-Film-Festival-37.jpg" },
    { filename: "China-Nature-Film-Festival-38.jpg" },
    { filename: "China-Nature-Film-Festival-39.jpg" },
    { filename: "China-Nature-Film-Festival-40.jpg" },
    { filename: "China-Nature-Film-Festival-41.jpg" },
    { filename: "China-Nature-Film-Festival-42.jpg" },
    { filename: "China-Nature-Film-Festival-43.jpg" },
    { filename: "China-Nature-Film-Festival-44.jpg" },
    { filename: "China-Nature-Film-Festival-45.jpg" },
    { filename: "China-Nature-Film-Festival-46.jpg" },
    { filename: "China-Nature-Film-Festival-47.jpg" },
    { filename: "China-Nature-Film-Festival-48.jpg" },
    { filename: "China-Nature-Film-Festival-49.jpg" },
    { filename: "China-Nature-Film-Festival-50.jpg" },
    { filename: "China-Nature-Film-Festival-51.jpg" },
    { filename: "China-Nature-Film-Festival-52.jpg" },
    { filename: "China-Nature-Film-Festival-53.jpg" },
    { filename: "China-Nature-Film-Festival-54.jpg" },
    { filename: "China-Nature-Film-Festival-55.jpg" },
    { filename: "China-Nature-Film-Festival-56.jpg" },
    { filename: "China-Nature-Film-Festival-57.jpg" },
    { filename: "China-Nature-Film-Festival-58.jpg" },
    { filename: "China-Nature-Film-Festival-59.jpg" },
    { filename: "China-Nature-Film-Festival-60.jpg" },
    { filename: "China-Nature-Film-Festival-61.jpg" },
    { filename: "China-Nature-Film-Festival-62.jpg" },
    { filename: "China-Nature-Film-Festival-63.jpg" },
    { filename: "China-Nature-Film-Festival-64.jpg" },
    { filename: "China-Nature-Film-Festival-65.jpg" },
    { filename: "China-Nature-Film-Festival-66.jpg" },
    { filename: "China-Nature-Film-Festival-67.jpg" },
    { filename: "China-Nature-Film-Festival-68.jpg" },
    { filename: "China-Nature-Film-Festival-69.jpg" },
  ]
}

export const press = {
  path: "press-coverage",
  images: [
    { filename: "Kiro-Urdin-0-Loeil-1024x670.jpg" },
    { filename: "Kiro-Urdin-84-85-1024x730.jpg" },
    { filename: "Kiro-Urdin-Ars-Nova-Magazine-1024x451.jpg" },
    { filename: "Kiro-Urdin-BeauxArts-1-1024x678.jpg" },
    { filename: "Kiro-Urdin-BeauxArts-2-960x1024.jpg" },
    { filename: "Kiro-Urdin-Cimaise1-1024x687.jpg" },
    { filename: "Kiro-Urdin-Cimaise2-1024x687.jpg" },
    { filename: "Kiro-Urdin-Debbie-Wilson-Globe-and-Mail-791x1024.jpg" },
    { filename: "kiro-urdin-el-nuevo-dia-876x1024.jpg" },
    { filename: "Kiro-Urdin-Independent-Film-Quarterly-3-1024x699.jpg" },
    { filename: "Kiro-Urdin-Jet-Society-1024x659.jpg" },
    { filename: "Kiro-Urdin-Le-Dessin-750x1024.jpg" },
    { filename: "Kiro-Urdin-Le-Dessin2-1024x774.jpg" },
    { filename: "Kiro-Urdin-LEcho-1024x675.jpg" },
    { filename: "Kiro-Urdin-Paris-Match-1024x471.jpg" },
    { filename: "Kiro-Urdin-San-Juan-Puerto-Rico-1024x632.jpg" },
    { filename: "Kiro-Urdin-Skanska-Dagbladet-1024x721.jpg" },
    { filename: "Kiro-Urdin-Vernisagge-1-1024x712.jpg" },
    { filename: "Kiro-Urdin-Vernisagge-21-1024x720.jpg" },
    { filename: "KiroUrdin-Geneve-EuropArt.jpg" },
    { filename: "Kiru_Urdin_Press_San_Juan-1024x611.jpg" },
    { filename: "The-Aspen-Times-1024x737.jpg" },
  ]
}

export const artworkMenuSlide = [
  {
    title: "Planetarium",
    album: "planetarium",
    thumb: planetarium.images[18].filename,
    link: "/photo-gallery/planetarium",
    column: "1 / span 5",
    row: "1 / span 3",
  },
  {
    title: "Watercolours",
    album: "watercolours",
    thumb: watercolours.images[1].filename,
    link: "/artwork/watercolours",
    column: "3 / span 3",
    row: "4 / span 2",
  },
  {
    title: "Drawings",
    album: "drawings",
    thumb: drawings.images[3].filename,
    link: "/artwork/drawings",
    column: "6 / span 3",
    row: "3 / span 2",
  },
  {
    title: "Paintings",
    album: "paintings",
    thumb: paintings.images[83].filename,
    link: "/artwork/paintings",
    column: "8 / span 3",
    row: "1 / span 2",
  },
  {
    title: "Sculptures",
    album: "sculptures",
    thumb: sculptures.images[0].filename,
    link: "/artwork/sculptures",
    column: "9 / span 3",
    row: "4 / span 2",
  },
  {
    title: "Photography",
    album: "omo-valley",
    thumb: omoValley.images[0].filename,
    link: "photo-gallery/tribes-of-omo-valley",
    column: "11 / span 3",
    row: "2 / span 2",
  },
  {
    column: "6 / span 2",
    row: "1 / span 2",
  },
  {
    column: "12 / span 2",
    row: "4 / span 2",
  },
  {
    column: "1 / span 2",
    row: "4 / span 2",
  },
  {
    column: "6 / span 3",
    row: "5 / span 1",
  },
  {
    column: "11 / span 3",
    row: "1 / span 1",
  },
  {
    column: "9 / span 2",
    row: "3 / span 1",
  }
]

export const projectsMenuSlide = [
  // {
  //   column: "11 / span 3",
  //   row: "2 / span 2",
  // },
  // {
  //   column: "11 / span 3",
  //   row: "1 / span 1",
  // },
  {
    type: "video",
    title: "Films",
    // album: "paintings",
    thumb: "films.mp4",
    link: "/artwork/paintings",
    column: "9 / span 5",
    row: "3 / span 3",
  },
  {
    title: "Poetry",
    album: "drawings",
    thumb: drawings.images[9].filename,
    link: "/artwork/drawings",
    column: "3 / span 3",
    row: "3 / span 2",
  },
  {
    title: "Aphorisms",
    album: "thumbs",
    thumb: "script.jpg",
    link: "/artwork/drawings",
    column: "6 / span 3",
    row: "1 / span 2",
  },
  {
    title: "Ballet",
    album: "thumbs",
    thumb: "planetarium_dance.jpg",
    link: "/artwork/paintings",
    column: "1 / span 5",
    row: "1 / span 3",
  },
  {
    title: "Photography",
    album: "omo-valley",
    thumb: omoValley.images[0].filename,
    link: "photo-gallery/tribes-of-omo-valley",
    column: "6 / span 3",
    row: "4 / span 2",
  },
  {
    title: "ZZZ",
    album: "sculptures",
    link: "/artwork/sculptures",
    thumb: sculptures.images[1].filename,
    link: "/artwork/sculptures",
    column: "11 / span 3",
    row: "1 / span 2",
  },
  {
    column: "4 / span 2",
    row: "1 / span 2",
  },
  {
    column: "1 / span 2",
    row: "4 / span 2",
  },
  {
    column: "6 / span 3",
    row: "3 / span 1",
  },
  {
    column: "3 / span 3",
    row: "5 / span 1",
  },
  {
    column: "9 / span 2",
    row: "1 / span 2",
  },
  {
    column: "1 / span 2",
    row: "3 / span 1",
  }
]
